### ISSUE TITLE
qmake on Linux fails: Project ERROR: Unknown module(s) in QT: qml

### ISSUE THREAD

**Issue by melissaboiko** [splintermind/Dwarf-Therapist#111]
Debian jessie, updated for today.  Following instructions in BUILDING.txt.

``` bash
$ git log | head -n 1
commit ae8d582e064ff56965a83dc795fa450487b4005f

$ qmake --qt=5 --version
QMake version 3.0
Using Qt version 5.3.1 in /usr/lib/x86_64-linux-gnu

$ qmake --qt=5
Project MESSAGE: Release Mode
Project MESSAGE: Setting up for Linux
Project ERROR: Unknown module(s) in QT: qml
```

All packages mentioned in BUILDING.txt are installed, as well as `qml` and `libqt5qml5`.  I tried to go ahead and install all Debian packages with 'qml' in the name, but no dice.

**Comment by Hello71** [comment]
did you install qtdeclarative5-dev too? there is an error in the command (my bad) which does not list it.

**Comment by melissaboiko** [comment]
I hadn't, and it works now! Thank you very much!
