### ISSUE TITLE
Rewrite truncatingfilelogger to print to stderr

### ISSUE THREAD

**Issue by Hello71** [splintermind/Dwarf-Therapist#114]
i.e. qInstallMessageHandler. i'm not entirely sure what the point of writing an entirely new logger when qt has a perfectly functional one was.

**Comment by splintermind** [comment]
Snide remarks aside, I can only assume that [at the time the logger was written](https://code.google.com/p/dwarftherapist/source/detail?r=31853f1622585016d057bf84cb61e9823d773620) no such libraries existed or they weren't sufficient for the task. Perhaps it was just overlooked.

**Comment by Hello71** [comment]
oh, log by namespace. is that used?

**Comment by Hello71** [comment]
I vaguely recall having written some code to write logs to stderr, but I'm not sure where I put it.

**Comment by Hello71** [comment]
> Snide remarks aside, I can only assume that at the time the logger was written no such libraries existed or they weren't sufficient for the task. Perhaps it was just overlooked.

looks like that's the case. [QLoggingCategory](http://qt-project.org/doc/qt-5/qloggingcategory.html) only exists in Qt 5.2+.
