### ISSUE TITLE
Recommendation for building on Linux distros which do not have qt5 provided

### ISSUE THREAD

**Issue by vrga** [splintermind/Dwarf-Therapist#115]
So, after fiddling for a while to manage to get new dt to compile on funtoo, no qt5 available in the repos, nor would i like to pull it into the full system, i've got the following steps.

Also, the assumption is that gcc is available systemwide...

get qt5 from [here](http://qt-project.org/downloads)
install wherever into your local users folder, i've installed qt5.3 amd64, gcc 64-bit only.
get dt and put it wherever locally and go into that folder
run the following command

```
~/.local_install/qt5/5.3/gcc_64/bin/qmake
```

replace ~/.local_install/qt5 with the path to wherever you installed yours and run

```
make
```

optionally with -j<number of cores>

copy etc folder from dt root to dt root/bin/release
run DwarfTherapist
observe it run

anyhow, the ability to define a custom installation dir / documenting it somewhere would be great.
i refuse to install DT system-wide and if you recommend that, shame on you.

as a side note, i tried compiling it with the provided qtcreator, but it just complains about the qtcolorpicker.moc not being available, which i assume means that moc is not executed for some reason properly when called through qtcreator, since the compile works well when compiled manually.

Sorry for the ugly half-finished braindump, but if nothing else, someone else who just wants to get DT to work on distros without QT5 might find this useful.

**Comment by Hello71** [comment]
so you'd rather the magic and unfixed bugs and security vulnerabilities of a random installation over the controlled updates of a package manager? I'll pass.

**Comment by vrga** [comment]
Which part of "no qt5 available in the repos" did you not understand?
As for the rest, indeed, indeed, i would not recommend it too much. 
But this: 
  A) minimizes the system-wide impact 
  B) allows you to use DT on a distro that does not officially support qt5 yet.
  C) i explicitly stated that i do not like installing this system-wide. neither qt5 nor dt.

Please read the complete report again.

**Comment by anders-larsson** [comment]
FYI issue #108 will add support for qt4.

**Comment by vrga** [comment]
Indeed, I saw that and I look forward to it being included.

**Comment by Hello71** [comment]
conjecture: people are more likely to read things that are organized in a remotely coherent manner.

**Comment by vrga** [comment]
Conjecture 2: people expect a modicum of politeness and common sense.
Also, please stop this, it is irrelevant to the "issue" at hand.
