### ISSUE TITLE
DF2014: set nickname has no effect

### ISSUE THREAD

**Issue by myk002** [splintermind/Dwarf-Therapist#123]
Setting a custom nickname for a dwarf, then committing, has no effect.  The new name does not show up in-game or in the DT UI after re-reading dwarf info.

Linux, DF: 0.40.08, DT: DF2014

**Comment by anders-larsson** [comment]
It does not appear to work to set custom profession names with 0.40.08 either. It can successfully load custom professions set in-game.

I've tried to figure out how to fix it. Found this https://code.google.com/p/dwarftherapist/wiki/MappingNewVersions but it didn't help me to understand how to fix it.

**Comment by Hello71** [comment]
this is related to the new process_vm changes; I am investigating.

**Comment by splintermind** [comment]
Currently any string writing is broken on linux (custom professions, nicknames, squad names, etc.)

In a brief test reverting the calls from<code>write_raw</code> to <code>write_raw_ptrace</code> in <code>DFInstanceLinux::remote_syscall</code> seemed to work. While I wouldn't call it a solution it may help narrow down exactly where the problem is occurring.

**Comment by Hello71** [comment]
the issue is that DT is trying to write into memory that's mapped as read-only since it's from the executable file. `ptrace` might be ignoring this read-only flag.

**Comment by Hello71** [comment]
```
2014-Aug-20 10:29:54.806 DEBUG  core    WRITE_RAW_PTRACE: WILL WRITE 4 BYTES FROM "00000000007302b4" TO "0x080514f0" OVER 1 STEPS, WITH STEPSIZE  8 [src/dfinstancelinux.cpp:272] (write_raw_ptrace)

08048000-0916a000 r-xp 00000000 08:11 135917                             /opt/dwarf-fortress/libs/Dwarf_Fortress
```

**Comment by splintermind** [comment]
It's a similar reason for the 'bad address' reports when reading strings. Calling the ptrace read after a failed process_vm_read read has no problems.

**Comment by Hello71** [comment]
instead of looking for nops in the executable code, I believe the correct solution is to push a stack frame and put the code there instead.

**Comment by Hello71** [comment]
actually, the current solution is more or less correct; the code relied on the ptrace properties, and getting a rwx page is impossible with pax anyways.
