### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: qml

### ISSUE THREAD

**Issue by BeauBouchard** [splintermind/Dwarf-Therapist#127]
when using the instructions [here](https://github.com/splintermind/Dwarf-Therapist/blob/DF2014/BUILDING.txt) 

> "qmake -qt=5"
> causes the error: Project ERROR: Unknown module(s) in QT: qml

Making it with qt 4 works fine, recommend instructions just say "qmake"

**Comment by myk002** [comment]
what version of qt5 are you using?  It builds just fine for me with qt-5.3.1
To be clear, I have qt4 installed at the system level, and a qt5 binary tarball downloaded and expanded in my $HOME/bin directory.  To build with qt4, I run:

```
qmake
make -j3
```

and to build with qt5 I run:

```
../../bin/Qt5.3.1/5.3/gcc_64/bin/qmake
make -j3
```

**Comment by BeauBouchard** [comment]
foolish me, updated and it works, It was a version issue.
