### ISSUE TITLE
DT 24.0 won't compile on osx

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#129]
/DwarfTherapist-git/src/dfinstanceosx.mm:219: error: no matching function for call to 'vm_read_overwrite'
        result = vm_read_overwrite(m_task, ptr, step_size,
                 ^~~~~~~~~~~~~~~~~

**Comment by splintermind** [comment]
Try replacing <code>(vm_address_t)</code> with <code>(mach_vm_address_t)</code>.

**Comment by fricy** [comment]
still doesn't like it

**Comment by fricy** [comment]
oops, I missed a detail that might be important, this belongs to the same error:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/mach/vm_map.h:181: candidate function not viable: no known conversion from 'USIZE *' (aka 'unsigned int *') to 'vm_size_t *' (aka 'unsigned long *') for 5th argument
kern_return_t vm_read_overwrite
              ^

vm_map.h:L181-188:

kern_return_t vm_read_overwrite
(
    vm_map_t target_task,
    vm_address_t address,
    vm_size_t size,
    vm_address_t data,
    vm_size_t *outsize
);

**Comment by splintermind** [comment]
At the start of the function change <code>SIZE readsize = 0;</code> to <code>vm_size_t readsize = 0;</code>

You can revert that first suggestion as well.

**Comment by fricy** [comment]
thx!
