### ISSUE TITLE
OSX: setting nicknames/custom professions

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#130]
About: 0722d77b9da1050da74c2a4da12a8071e2b44883 - comment says this can crash DF, 
but there's also 0660a79f9e73f3ebce3b17e5e3afb9bb9733a485 which seems to work ok. Is there a reason for not using 0660..?

**Comment by splintermind** [comment]
That was unintentional. It seems there were some merges after the 0660a79 which reverted a few of the changes. I've re-applied the patch in [this commit](https://github.com/splintermind/Dwarf-Therapist/commit/5ed019813ddffacbf0172c7d9fb6e64a10d0bd90#diff-d41d8cd98f00b204e9800998ecf8427e).
