### ISSUE TITLE
Animal Caretaker

### ISSUE THREAD

**Issue by wlmartin** [splintermind/Dwarf-Therapist#138]
Within the Labors Tab, animal caretaker is not included for 2014

I only noticed this when i had to try and find out why one dwarf still had an assigne labor and found it under roles

**Comment by splintermind** [comment]
Yeah I'd intentionally left out the two useless alchemy and animal care labors, but since it keeps coming up I'm just going to add them back in.

**Comment by wlmartin** [comment]
Understood

I just think that it leaves a gap is all. Otherwise, love the changes and
improvements.. very good
