### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by jaswilliams** [splintermind/Dwarf-Therapist#153]
_Copied from Bay12 forums with additional requested info:_

I ran into some trouble running it; I'd be grateful for any help:

`/usr/bin/DwarfTherapist: error while loading shared libraries: libQt5Qml.so.5: cannot open shared object file: No such file or directory`

My distro is Crunchbang 11, based on Debian 7. As far as I understand it, Qt5 isn't supported. I tried following the instructions to build from source and "qmake" gave me this:

`Project MESSAGE: Release Mode`
`Project MESSAGE: Setting up for Linux`
`Project MESSAGE: Warning: unknown QT: concurrent`
`Project MESSAGE: Warning: unknown QT: widgets`

After that I ran "make -j$(nproc)" anyway to see what would happen. Result:

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/dfinstancelinux.o src/dfinstancelinux.cpp`

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/memorylayout.o src/memorylayout.cpp`

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/mainwindow.o src/mainwindow.cpp`

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/main.o src/main.cpp`

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/importexportdialog.o src/importexportdialog.cpp`

`src/dfinstancelinux.cpp: In member function ‘virtual int DFInstanceLinux::read_raw(const VIRTADDR&, USIZE, QByteArray&)’:`

`src/dfinstancelinux.cpp:240:72: error: ‘process_vm_readv’ was not declared in this scope`

`src/dfinstancelinux.cpp: In member function ‘virtual int DFInstanceLinux::write_raw(const VIRTADDR&, const USIZE&, void*)’:`

`src/dfinstancelinux.cpp:321:76: error: ‘process_vm_writev’ was not declared in this scope`

`make: *** [bin/release/dfinstancelinux.o] Error 1`

`make: *** Waiting for unfinished jobs....`

Are there any relatively easy ways to fix this (that is, without installing a different distro or risking the operation of my current system)?

Thanks,
James

**Comment by Hello71** [comment]
what version of glibc are you running? `dpkg-query -W -f='${Version}' libc6`

**Comment by jaswilliams** [comment]
2.13-38+deb7u32.13-38+deb7u3

**Comment by Hello71** [comment]
that's old as balls. pull in weak from Hello71/Dwarf-Therapist and try again.

```
git pull .../Hello71/Dwarf-Therapist weak
```

#151

**Comment by jaswilliams** [comment]
It works! Thanks so much, particularly for the quick response.
