### ISSUE TITLE
Path to manual is wrong on Linux

### ISSUE THREAD

**Issue by wRAR** [splintermind/Dwarf-Therapist#160]
When trying to open the manual via the menu item I get an error that "file://file:/usr/bin/Therapist Manual.pdf" doesn't exist. The code uses applicationDirPath which is wrong but I cannot say anything right now about the duplicate file:.

**Comment by Hello71** [comment]
well, don't blame me on this one.

**Comment by Hello71** [comment]
somewhat easily fixed with application of find_files_list. unfortunately, then it's required to _install_ the manual too, which I'm hesitant to do due to its age.

**Comment by wRAR** [comment]
Well if the manual is really that outdated maybe remove the menu option?

**Comment by splintermind** [comment]
29 days really isn't that outdated, and it's better than nothing. I won't be removing the menu, the manual just needs to be added to the source and installed, and of course the broken path fixed.

Previously I was only adding it when I'd package things up for a release, but obviously that does screw anyone building from source.

**Comment by wRAR** [comment]
From a (Debian) packaging perspective it would be interesting to include the manual LaTeX source (maybe as a submodule) into the DT tree but maybe I'm asking too much.

**Comment by splintermind** [comment]
I think that sounds reasonable... and should be a nice solution for packaging the PDF (or LaTeX) for releases. I haven't ever setup a submodule with git so I'll have to look into it.

**Comment by Hello71** [comment]
i'll get to this sometime today.

**Comment by Hello71** [comment]
been busy, ran into some cross-platform compatibility issues. will send patch in soon.

**Comment by Hello71** [comment]
fixed by #185, &c.
