### ISSUE TITLE
Fix various invalid code errors found by clang.

### ISSUE THREAD

**Issue by Hello71** [splintermind/Dwarf-Therapist#169]
some of these need pretty heavy refactoring. if this were bugzilla, I'd assign this to myself.

**Comment by Hello71** [comment]
https://happinessforme.com/~alex/scan-build-2014-09-15-124540-9784-1
https://happinessforme.com/~alex/scan-build-2014-09-15-124540-9784-1.tar.xz

**Comment by splintermind** [comment]
Looks like the links are bad

**Comment by Hello71** [comment]
no, my hoster is just completely !@#$ed and has no idea what the concept of "services" is. i haven't found time to move yet.
