### ISSUE TITLE
Mass nickname your dwarfs from a file

### ISSUE THREAD

**Issue by sisso** [splintermind/Dwarf-Therapist#171]
Should be nice if we are able to nickname your dwarves from a external text file. 

If someone could point me I could give a try in the code:
- added a new item menu
- get list of all dwarves
- change nickname

**Comment by splintermind** [comment]
What is the external file for, and why would you want to do this instead of just choosing the dwarfs in DT and mass nicknaming?

**Comment by sisso** [comment]
I didn't understood the exact meaning of "mass nicknaming", is there a tool that automatic nickname dwarfs or did you say to manually nickname all my dwarfs, one at time?

I will try to explain my intention by showing my current and the desired work flow. 

Current work flow:
1. For each new game or emigration
2. Open therapist and sort dwarves by emigration
3. For each new dwarf
   1. right click, change nickname,
   2. think a nickname, verify if was not used yet, and then write new nickname

Desired work flow:
1. Write into a txt/csv file a list of nicknames (my friends, interesting names or youtube followers)
2. For each new game or emigration
   1. Load open therapist 
   2. File -> Import nicknames from file
   3. Choose my file
   4. The therapist assign a unused nickname from the file for each dwarf without nickname

**Comment by splintermind** [comment]
Oh. So for succession games or streams, you want to have a file of all pending nicknames, and each time you assign nickname(s), it grabs the first available one from the file?

**Comment by sisso** [comment]
These are some use. But for me is simply don't write 15 new nicknames each time that I receive an emigration.

The easy way to talk, is with code :P

```
  function assignNicknamesFromFile(String filename, List<Dwarf> dwarfs) 
  {
    // read file with many nicknames, one each line
    List<String> nicknames = readFile(filename).split("\n");

    // remove all already used nicknames from my list
    for(int i = 0 ; i < dwarfs.size ; i ++) 
      if (dwarfs[i].hasNickname()) 
        nicknames.remove(dwarfs[i].getNickname());

    // for each dwarf
    for (var i = 0 ; i < dwarfs.size ; i ++) 
    {
      Dwarf d = dwarfs[i];
      // check if it didn't have a nickname
      if (!d.hasNickname()) 
      {
        // take next available and assign
        String nextNickname = nicknames.removeFirst();
        d.setNickname(nextNickname);
      }
    }
  }
```
