### ISSUE TITLE
Add a message about setting up Qt 4 or Qt 5 to the .pro file

### ISSUE THREAD

**Issue by stoutheart** [splintermind/Dwarf-Therapist#172]
## As per the title the patch is below the line.

diff --git a/dwarftherapist.pro b/dwarftherapist.pro
index ad4a9f7..71d809b 100644
--- a/dwarftherapist.pro
+++ b/dwarftherapist.pro
@@ -2,9 +2,11 @@ TEMPLATE = app
 TARGET = DwarfTherapist
 QT += concurrent widgets
 lessThan(QT_MAJOR_VERSION, 5) {
-    message(Setting up for Qt 4)
   QT += script
  }
  else {
-    message(Setting up for Qt 5)
   QT += qml
  }
  CONFIG += debug_and_release \

**Comment by Hello71** [comment]
lgtm. submit a pull request.

**Comment by splintermind** [comment]
Fixed in #179
