### ISSUE TITLE
Some of the gridviews have size=x longer than the data

### ISSUE THREAD

**Issue by stoutheart** [splintermind/Dwarf-Therapist#173]
## As per title.  The patch is below the line.

diff --git a/share/default_gridviews.dtg b/share/default_gridviews.dtg
index 788e779..a32a9a0 100644
--- a/share/default_gridviews.dtg
+++ b/share/default_gridviews.dtg
@@ -72,7 +72,7 @@ size=11
 2\sets\size=18
 2\sets\1\name=General
 2\sets\1\bg_color=0xffffffff
-2\sets\1\columns\size=5
+2\sets\1\columns\size=4
 2\sets\1\columns\1\name=Current Job
 2\sets\1\columns\1\type=IDLE
 2\sets\1\columns\2\name=Happiness
@@ -399,7 +399,7 @@ size=11
 3\sets\size=18
 3\sets\1\name=General
 3\sets\1\bg_color=0xffffffff
-3\sets\1\columns\size=5
+3\sets\1\columns\size=4
 3\sets\1\columns\1\name=Current Job
 3\sets\1\columns\1\type=IDLE
 3\sets\1\columns\2\name=Happiness
@@ -968,7 +968,7 @@ size=11
 4\sets\7\columns\8\width=4
 4\sets\8\name=Military Roles
 4\sets\8\bg_color=0xffffffff
-4\sets\8\columns\size=6
+4\sets\8\columns\size=5
 4\sets\8\columns\1\name=SPACER
 4\sets\8\columns\1\type=SPACER
 4\sets\8\columns\2\name=Armor User
@@ -982,6 +982,7 @@ size=11
 4\sets\8\columns\4\role_id=Teacher
 4\sets\8\columns\5\name=Student
 4\sets\8\columns\5\type=ROLE
+4\sets\8\columns\5\role_id=Student
 4\sets\9\name=Gear
 4\sets\9\bg_color=0xffffffff
 4\sets\9\columns\size=12

**Comment by splintermind** [comment]
Fixed in #178
