### ISSUE TITLE
get_noble_color fails if m_nobles.value(x) returns size == 0

### ISSUE THREAD

**Issue by stoutheart** [splintermind/Dwarf-Therapist#174]
## As per the title.  The patch is below the line.

diff --git a/src/fortressentity.cpp b/src/fortressentity.cpp
index 8a635ca..58fe822 100644
--- a/src/fortressentity.cpp
+++ b/src/fortressentity.cpp
@@ -215,11 +215,9 @@ QString FortressEntity::get_noble_positions(int hist_id, bool is_male){

 QColor FortressEntity::get_noble_color(int hist_id){
     QList<position> p = m_nobles.values(hist_id);
-    if(p.size() > 1)
-        return m_noble_colors.value(MULTIPLE);
-    else
-    if(p.size() == 1){
       return p[0].highlight;
  -
-    }
   return m_noble_colors.value(MULTIPLE); //unknown
  }

**Comment by splintermind** [comment]
Fixed in #177
