### ISSUE TITLE
Error while building on Linux

### ISSUE THREAD

**Issue by latias1290** [splintermind/Dwarf-Therapist#18]
# question

(I have absolutely no idea how to tag issues, so Ill do it like this)
I was building the source to run on Linux. Ran the make command, got this error:

> make: g++: Command not found
> make: **\* [bin/release/dfinstancelinux.o] Error 127

How to fix?

**Comment by splintermind** [comment]
try replacing makefile with makefile_linux

**Comment by latias1290** [comment]
You mean just deleting makefile and renameing makefile_linux to makefile? Because makefile_linux already exists in my clone directory.

Edit: Since there is no precompiled release available that works directly, would it be an idea if I build it and submit the program for each release?

**Comment by splintermind** [comment]
yeah another user updated and submitted a special linux makefile, so replacing it exactly as you've described should work (unless it's another problem).

if you're willing to build and package it up, that would be awesome.

**Comment by latias1290** [comment]
Building the source gave me 2 warnings. Since they were warnings, they didnt halt the compiler and the source is built.

However, I am a big noob to github, so where do I find the compiled program so I can pack it?

**Comment by splintermind** [comment]
The compiled executable should be in the source's bin/release directory. You'll also need to include the /etc folder, and probably have to do some work to find all the necessary libraries.

**Comment by latias1290** [comment]
Im still busy finding neccesary libs, but I forgot to mention 1 thing; replacing makefile didnt work - I googled the error and found out I didnt have the g++ command installed. =P

**Comment by latias1290** [comment]
Ill have to point out that theres something wrong in the BUILDING.txt file. It says "to run the program,  do sudo dwarftherapist". However, you need to do "sudo DwarfTherapist". The Linux terminal is case-sensitive, at least Zorin's terminal is.

**Comment by splintermind** [comment]
I've updated the BUILDING.txt as you've recommended.

**Comment by latias1290** [comment]
Oh, and another thing: while looking for the things needed to install based off the things you needed to remove to uninstall, and I found that "/etc/bin/dwarftherapist" does not exist.

Im pretty much done with packing now, just need to write instructions and Ill upload the file.

**Comment by latias1290** [comment]
Finished. I have a text file with installation and uninstallation instructions, as well as how to run it. I also have a .tar.gz file containing the necessary files.

Where do I upload it?

**Comment by latias1290** [comment]
Turns out that you need to start it inside the DT github clone folder, which could mean that this isnt going to be possible. Yeah.

**Comment by splintermind** [comment]
Someone else recently posted that same error in the main thread on the DF forums. I still don't know what the cause of it is.

**Comment by latias1290** [comment]
Started it. Now this happened; there is nothing in any tab except for the animals tab, which shows all animals and dwarves.

=U

**Comment by latias1290** [comment]
Never mind.

Tip: Dont start DT while your fort is loading.

**Comment by splintermind** [comment]
Hrmm I was just able to reproduce it by running sudo DwarfTherapist. However, running from the bin/release directory was fine..

Did you resolve the issue then? What's causing it?

**Comment by latias1290** [comment]
Well, I didnt actually resolve it. I only noticed that running DT from any directory other than the github folder would result in an error.

**Comment by splintermind** [comment]
I've removed "/etc/bin/dwarftherapist" from the BUILDING instructions. And indeed, running from within the github directory doesn't result in that QProcess error.

**Comment by splintermind** [comment]
Alright, so running the dwarftherapist script in /usr/bin seems to work from anywhere. Can you test that out?

**Comment by latias1290** [comment]
It works. However, it says "need to run as root because user ptrace is disabled" and hangs for a while, leading me to think that it doesnt work. It does, however.

I may also want to learn bash or sh scripts sometime and make a more automated installation script(the current instructions are manual).

Also, now that its working, where do I upload the package?

**Comment by splintermind** [comment]
Alright, well I guess I should change those build instructions to point users to sh dwarftherapist, as opposed to sudo DwarfTherapist?

You can upload it wherever you'd like, and I'll create a link to it on the main page. Currently the OSX and Windows versions are packaged and hosted on http://dffd.wimbli.com/
