### ISSUE TITLE
osx layout config problem

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#190]
The new config syntax doesn't work (layouts.files += share/memory_layouts/osx/*)

make[1]: **\* No rule to make target `share/memory_layouts/osx/*', needed by`release/DwarfTherapist.app/Contents/MacOS/share/memory_layouts/osx/v0.40.04_osx.ini'.  Stop.
make: **\* [release] Error 2
21:51:28: The process "/usr/bin/m

**Comment by Hello71** [comment]
I didn't change that. might have been caused by build_pass scope though. shitty qmake docs.

wait, no. @splintermind b0rked that by moving everything to resources/.

**Comment by splintermind** [comment]
I changed it to avoid having to add every layout file individually, but
yeah, no mac to actually test it.

**Comment by splintermind** [comment]
> wait, no. @splintermind b0rked that by moving everything to resources/.

Memory layout files have nothing to do with the resources. game_data.ini though..
