### ISSUE TITLE
DT 26.0+ creates two dock icons, full screen mode is wonky

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#199]
Screenshot: http://imgur.com/ISHuo54  

You can see two annoying problems on this screenshot:  
1, In 26.0 and 27.0 launching DT creates two app icons in the dock and also in the CMD-Tab taskswitcher. Also [this report says it's unstable.](http://www.bay12forums.com/smf/index.php?topic=128960.msg5683796#msg5683796)
2, The second problem is that fullscreen mode doesn't work correctly on OSX. If I launch DT without DF running, it fills the screen correctly until the connect dialog comes up.When I connect to the game the app window resizes, and the right dock will be partly off screen as seen in the screenshot. If I set fill screen mode again, it resizes, but adding any new docks will cause the app window the enlarge again. My resolution is 1280x800, I haven't tested this with different resolution.

**Comment by Hello71** [comment]
the first has to do with the authorization; it needs to be called before the qapplication is started, but apparently there were some issues with getting the right one called; patches to fix that while maintaining windows/linux compatibility would be great

**Comment by Hello71** [comment]
the second appears only to be an issue for qt4 builds; I really don't want to go fishing in the UI code.

**Comment by fricy** [comment]
Additional info for authorization: QCoreApplication::setSetuidAllowed(true) should be a conditional statement, it's only needed on QT 5.3+, compiling on anything lower will fail.  

And 2, is present with both qt5 and qt4.8 builds. Now that DT works with qt4.8 I think I'd stick with that.

**Comment by fricy** [comment]
Naive question: Wouldn't it work if one of the spawned windows was hidden with Qwidget::hide() ?

**Comment by Hello71** [comment]
the first is fixed by #165.

**Comment by lethosor** [comment]
Bizarrely, ddef98e fixes the first problem (at least for me on 10.9).
I'm not sure exactly what #165 would involve, but I could take a look.

**Comment by fricy** [comment]
confirmed to work on 10.7 too. New build uploaded. :)

**Comment by lethosor** [comment]
@fricy regarding the second issue, I don't see any sort of full screen option (at least on 10.9). If you mean #232, does a92d294 fix the problem?

**Comment by fricy** [comment]
Not full screen, fill screen (little green button top left corner)  
Resolving in favor of 232.
