### ISSUE TITLE
Equipments are not displayed on OSX (DT 23.6+)

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#200]
Posting a reminder since [this issue is](http://www.bay12forums.com/smf/index.php?topic=122968.msg5577312;topicseen#msg5577312) still present in 27.0. Could not make any further progress.
[Debug log file](https://dl.dropboxusercontent.com/u/36491887/DT_23.6_run.log) shows a problem with determining item type.

**Comment by fricy** [comment]
Run a comperative debug on the windows and osx versions to try to narrow down the problem. I added some additional debug lines to dwarf.cpp as per commit 569003c24e
The full logs can be found here: [win](https://dl.dropboxusercontent.com/u/36491887/debug-run-win.log) and [osx](https://dl.dropboxusercontent.com/u/36491887/debug-run-osx.log)

Suspect line is bolded, let me know if I found something.

**Windows:**
2014-nov.-02 15:54:33.775 DEBUG core    reading profession for "Tosid Iliden" 75 "Hammerman" [..\Dwarf-Therapist\src\dwarf.cpp:843](read_profession)
2014-nov.-02 15:54:33.781 DEBUG core    reading inventory for "Tosid Iliden" [..\Dwarf-Therapist\src\dwarf.cpp:1494](read_inventory)
2014-nov.-02 15:54:33.781 DEBUG core      + inv_type: 2 [..\Dwarf-Therapist\src\dwarf.cpp:1517](read_inventory)
**2014-nov.-02 15:54:33.782 DEBUG   core      + i_type: 25 [..\Dwarf-Therapist\src\dwarf.cpp:1529](read_inventory)**
2014-nov.-02 15:54:33.782 DEBUG core      + i: Item(0x203a4c10) [..\Dwarf-Therapist\src\dwarf.cpp:1530](read_inventory)
2014-nov.-02 15:54:33.782 DEBUG core      + found armor/clothing: "_Bronze Mail Shirt_ (Over)" [..\Dwarf-Therapist\src\dwarf.cpp:1565](read_inventory)

**OSX:**
2014-nov.-02 16:40:12.554 DEBUG core    reading profession for "Tosid Iliden" 75 "Hammerman" [../../Dwarf-Therapist/src/dwarf.cpp:843](read_profession)
2014-nov.-02 16:40:12.562 DEBUG core    reading inventory for "Tosid Iliden" [../../Dwarf-Therapist/src/dwarf.cpp:1494](read_inventory)
2014-nov.-02 16:40:12.563 DEBUG core      + inv_type: 2 [../../Dwarf-Therapist/src/dwarf.cpp:1517](read_inventory)
**2014-nov.-02 16:40:12.564 DEBUG   core      + i_type: 431492332 [../../Dwarf-Therapist/src/dwarf.cpp:1529](read_inventory)**
2014-nov.-02 16:40:12.565 DEBUG core      + i: Item(0x10d488030) [../../Dwarf-Therapist/src/dwarf.cpp:1530](read_inventory)
2014-nov.-02 16:40:12.565 DEBUG core      + found other item: "_Bronze N/A_" [../../Dwarf-Therapist/src/dwarf.cpp:1570](read_inventory)

**Comment by splintermind** [comment]
I'd replied on the forums that this was the issue. [It's due to a hard-coded offset for the item type's returned value here.](https://github.com/splintermind/Dwarf-Therapist/blob/DF2014/src/item.cpp#L142)

The 0x1 is the issue, since there's apparently a difference with the OSX vtables. However, I don't know what the difference is since I don't have a mac to poke around in memory with, nor can I generate the df-structures for OSX.

**Comment by lethosor** [comment]
What part of df-structures would you need?

**Comment by splintermind** [comment]
"item","1","0x0","0x4","pointer","_vtable","item::vtable",""
and
"item::vtable","1","0x0","0x4","vmethod(0/0)","getType","item_type",""

I'd assume they're exactly the same on OSX, so it's just to confirm. Then it'll be a matter of looking at the getType function and finding the offset of the return value.

**Comment by fricy** [comment]
This seems to work:

m_iType = static_cast<ITEM_TYPE>(m_df->read_int(m_df->read_addr(item_vtable) + 0x4));
