### ISSUE TITLE
Copy dwarf name to New Nickname Dialog

### ISSUE THREAD

**Issue by ragundo** [splintermind/Dwarf-Therapist#210]
Hello

As mentioned in the user manual, it's good to assign a nickname with the profession to a dwarf in order to manage him effectively.
But, if, for example,  I want to nickname a dwarf called Ber Tileshkonos to [Carpenter]Ber Tileshkonos I need to write all the dwarf's name because the input texbox is empty when I select the assign nickname menu.

![image](https://cloud.githubusercontent.com/assets/9405614/4783643/239e2088-5d2f-11e4-88bf-c86cb7b1a0ae.png)

If the number of dwarfves is big, is a pain to copy all the names one by one. 
If the name of the dwarf is copied to the textbox and selected, is easy to add the profession, or any other attribute like [1MCarpenter...](Inmigrant wave, male, Profession, etc) to the name.

![image](https://cloud.githubusercontent.com/assets/9405614/4783658/ef433912-5d2f-11e4-990f-40697773e7e1.png)

Group all the dwarves by profession, select one by one and and paste [Carpenter] to each nickname and voila, all the carpenters have nicknames, ready to be easyli identified in Stonesense, for example.

If someone prefers to use another nickname, pressing DELETE will clear the textbox, and it will be ready to accept a new nickname from the user.

Greetings from Spain
PD. Sorry for my English

**Comment by splintermind** [comment]
I'm not sure I follow what you're trying to do here. The nickname is separate from the full name, why do you want to copy the full name into the nickname?

You can also select multiple units and set all the nicknames at once, instead of doing it one at a time.

**Comment by ragundo** [comment]
Hello.
You're right. You can assign the Profession to multiple selected dwarves. I didn't try it!!!

Also, I was thinking about Dwarf Therapist changing dinamically the nickname value as a sort of poor man ingame unit statistics. 
For example, generating a nickname like this one [2M8Carpenter]:
2 for a dwarf from the second inmigrant wawe,
M for male, 
8 for happiness 
Carpenter Profession, etc

![sin nombre](https://cloud.githubusercontent.com/assets/9405614/4784192/24ad9814-5d48-11e4-9ffd-c0a1aba5b166.png)

This way you can track easily your dwarves in DF and in StoneSense. It would be something similar to Filter Dwarves, but much simpler.

Anyway, thanks for this fantastic program, I'm going to download the source and study it.
