### ISSUE TITLE
Changes to Labor do not take place

### ISSUE THREAD

**Issue by Curt5** [splintermind/Dwarf-Therapist#212]
Not sure if this is the correct place to put this, but I've asked around elsewhere and received nothing, so I figured the DwarfTherapist bug page was the best. When I try to make changes to the labor my dwarves can do (For instance, say that my Carpenter isn't allowed to do Bowery, but can do Woodcrafting) the changes will appear to have taken place after I confirm the changes. However, nothing changes within the game, and when I re-read the dwarves, the changes are reverted. And because I'm using DwarfTherapist, I can't just go in the game and manually change the jobs, because Dwarf Therapist demands you use it to change the jobs rather than just hitting Enter to allow/disallow jobs. So I can't make my dwarves do anything they haven't already been doing (Except Mining, which somehow keeps it's changes and can be changed in-game) rendering me unable to play unless I just never use Dwarf Therapist and handle everything manually.
Am I just doing something wrong here, or is there an error?

**Comment by splintermind** [comment]
Are you committing the changes? Do you have dfhack with autolabor enabled?

DT does not force you to use it to change the labors. If you can't manually change the labors in game, then there's some other issue.

**Comment by Curt5** [comment]
I was! (I had been using the Starter's Pack and had been told what to do by a friend who didn't know what he was doing) However, now all that's on is DwarfTherapist and SoundSense, and I'm having the same issue. I'm doing it as the instruction book says: Click on job to unassign/assign, Move to tab on right with "Pending Changes," click Commit Changes, and it should work. But it doesn't, and I still can't manually change the jobs in-game. Any ideas?

**Comment by lethosor** [comment]
What does running "autolabor" in the DFHack console display?

**Comment by Curt5** [comment]
"Automatically assigns labors to dwarves. Activate with 'autolabor 1' and deactivate with 'autolabor 0'. Current state: 1

I'll just go ahead and turn that off then I thought I had
