### ISSUE TITLE
establishing 40.01 compatibility

### ISSUE THREAD

**Issue by nonymous** [splintermind/Dwarf-Therapist#22]
Hello,
I'm interested in helping with this project.

40.01 is shiny, new, and incompatible.

When you start mapping the memory, do you tend to use a memory dump?

**Comment by seemk** [comment]
Take a look here: https://code.google.com/p/dwarftherapist/wiki/MappingNewVersions

I tried mapping the new version today, but without success yet.

**Comment by nonymous** [comment]
Don't you think the new release will have enough differences to thwart that method?

I have gotten a crash dump off of a win 7 64 machine running 40.01, but I should probably re-do it with extreme skills and the easily searchable name.

**Comment by splintermind** [comment]
Once df-structures have been updated the scripts in the main directory can be used to generate the memory layout files.
