### ISSUE TITLE
DT Linux segfaults with DF 40.19

### ISSUE THREAD

**Issue by ldnunes** [splintermind/Dwarf-Therapist#220]
I'm getting a segfault while running DT when I try to open or add the "Labors Full" tab on the main view. 

Possibly related: my save was created before the "emotions" update of DF, and has been upgraded ever since. If needed I can provide the saved game.

I compiled DT with commit: d8d54e193dc119124fe0dab4eb205830e73e3f83, using QT 5.

Other infos:
OS: Linux ldnunes 3.16.0-4-amd64 #1 SMP Debian 3.16.7-2 (2014-11-06) x86_64 GNU/Linux
Debian Jessie

Log (collected using "DwarfTherapist 2> log.txt"): http://paste.debian.net/134729/

**Comment by Hello71** [comment]
please obtain a gdb backtrace, either manually (`bt full` preferable) or through qt creator (although I'm not sure how to capture the latter).

**Comment by Hello71** [comment]
you may also want to join #dwarftherapist on freenode.

**Comment by splintermind** [comment]
Please provide the save if possible as well, I haven't had any luck reproducing this yet.

**Comment by ldnunes** [comment]
GDB bt full: http://paste.debian.net/134760/
Save file: http://dffd.wimbli.com/file.php?id=10171

I'm "ldnunes" on Freenode.

**Comment by ldnunes** [comment]
I did some tests, and from what I could find with the help from the guys on #dwarftherapist@freenode I think this issue is specific to my system. Sorry for the noise.
