### ISSUE TITLE
.pro file doesn't respect PREFIX convention

### ISSUE THREAD

**Issue by Ramblurr** [splintermind/Dwarf-Therapist#225]
By default on linux the project file installs into /usr, which generally is configurable with a PREFIX variable but doesn't seem to be in the case of DT.

Would be great if that convention was supported.

**Comment by Hello71** [comment]
```
make INSTALL_ROOT=/wherever
```

want better solution? make a patch for `dwarftherapist.pro`. ensure that when prefix is not set, it defaults to /usr. I still haven't figured this out after half a year.

**Comment by Ramblurr** [comment]
@Hello71 Just submitted that patch. Closing this bug report now, refer to #226 instead.
