### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by moopie** [splintermind/Dwarf-Therapist#228]
Would be nice to add Dwarf Therapist to the [chocolatey](https://chocolatey.org/) repository.

**Comment by MEXAHOTABOP** [comment]
for what?
i dont think what many ppl use this

if you want you ofc can create package and support him

**Comment by Hello71** [comment]
@MEXAHOTABOP: please make some attempt at proper English.

@moopie: sure, but seeing as none of us (read: splinterz, lethosor, fricy &co) use it (far as I know), we won't be spending time on that. DT is a mostly-standard Qt application; follow whatever tutorial is out there for that. patches to improve "standards compliancy" will probably be accepted as long as they do not cause problems for other platforms.

**Comment by moopie** [comment]
Actually, now that I looked into it, the package itself doesn't have to be tied to the project itself.

I'll set it up. Probably will work on adding Dwarf Fortress to chocolatey too.
