### ISSUE TITLE
hauling cant be disabled

### ISSUE THREAD

**Issue by ghost** [splintermind/Dwarf-Therapist#249]
whenever i click on the hauling box for any dwarf, nothing happens. i can disable it in dwarf fortress, though, but it doesnt appear as being disabled in dwarf therapist.

**Comment by lethosor** [comment]
Are you using the autolabor or autohauler DFHack plugins?

**Comment by ghost** [comment]
nope! i dont even use DFHack, just dwarf therapist.

**Comment by splintermind** [comment]
If you're using the 'Labors Compact' view, the 'Hauling' column is actually a special kind of column that may not be configured.

Go to Windows->Docks->Customizations, and check that you have a Super Labor named 'Hauling'. If you do not, click the button at the bottom of the dock to create a new Super Labor column.
