### ISSUE TITLE
Help About should link to LGPL

### ISSUE THREAD

**Issue by bbarenblat** [splintermind/Dwarf-Therapist#256]
src/rolecalcbase.cpp is licensed under the [LGPL 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html), so to comply with section 6, the About box should

> include the copyright notice for the Library among them, as well as a reference directing the user to the copy of this License.

This should be a trivial change; the text in the About box needs to change, and that’s it.

**Comment by splintermind** [comment]
That should just be removed entirely. It's no longer using the code referenced and has since been completely re-written with a different method altogether.
