### ISSUE TITLE
[OSX] - 32.0 scrolling problem

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#261]
Hey,

Is there a minimum QT requirement for the new version? 'Cause I compiled the source with latest QT4 brew formula (4.8.7_1), and the resulting app has a problem with refreshing the screen contents when scrolling.
[Here's an album](http://imgur.com/a/rl7MM) to illustrate what happens with horizontal scrolling. Vertical scroll behaves the same. Moving the mouse over the grid restores/refreshes the line the mouse is over. DT settings were cleared before testing.

**Comment by splintermind** [comment]
I really can't say for QT4. Last I've tested it was with 5.1.1 (prior to version 32.0) and with 32.0 I'd updated to QT 5.4.2. QT 5.1.1 definitely has issues though.

AFAIK, nothing in regards to the views or scrolling was changed though. Does 31.0 have the same problem?

**Comment by fricy** [comment]
Closing this report. Further investigation indicates either a qt corruption on my build system, or a bug with qt 4.8.7. Reverting Qt to 4.8.6 (used to build 31.0) appears to have fixed this problem.
