### ISSUE TITLE
Feature Request: Replace/extend tooltips with a dockable viewport

### ISSUE THREAD

**Issue by nixnull** [splintermind/Dwarf-Therapist#267]
With the most recent version of the game, nearly all of the information in the tooltips has seen expansion. The default font and font size no longer always fits the entire tooltip on my 1080p screen. I can remedy this by decreasing the font size, but a more future-proof and pleasant solution might be to add a scrollable viewport that shows the selected dwarf's info.

**Comment by nixnull** [comment]
Apparently I forgot about the "Dwarf Details" window. I'll just go back to playing df...

**Comment by splintermind** [comment]
You can also use the 'Information' dock to re-direct tooltips to that dock window instead.
