### ISSUE TITLE
I can make linux builds if you'd like

### ISSUE THREAD

**Issue by dokipen** [splintermind/Dwarf-Therapist#268]
Here is one I made last night. I can make qt4 or qt5. I'm sure I could figure out how to make a 32bit release if you anyone needs it too.

https://github.com/dokipen/Dwarf-Therapist/releases

**Comment by epsilon-phase** [comment]
Would you mind just telling me what the dependencies are? My build is failing due to missing definitions for GameDataReader's methods... 

Never mind, seems to have resolved itself.

**Comment by cinead** [comment]
I would like to see some regular linux builds. I have been trying to get Dwarf Therapist to run on my Enlightenment OS/Luna laptop all day. 
I did finally manage to get it running just now and I discovered that the version of Dwarf Therapist I have doesn't match the version of Dwarf Fortress I have.
Is there a compatibility schedule for Dwarf Therapist? Does support get added for newer versions of Dwarf Fortress if I am patient?
Or is best to just install an older version of DF?
Thanks for your time.

**Comment by lethosor** [comment]
It depends on https://github.com/dfhack/df-structures - that's mostly working with 0.42.04 now, so I'll see if I can generate a Linux layout (which should hopefully work) shortly.

Edit: some unexpected issues on Linux, unfortunately. Will try again tomorrow.

**Comment by cinead** [comment]
Thanks for the prompt response!

**Comment by lethosor** [comment]
Splinterz has added better layouts here: https://github.com/splintermind/Dwarf-Therapist/tree/DF2016/share/memory_layouts

**Comment by l0rb** [comment]
+1 for regular Linux builds
