### ISSUE TITLE
Missing include file on Ubuntu 14.04

### ISSUE THREAD

**Issue by bkconrad** [splintermind/Dwarf-Therapist#27]
On revision c140b0ef41c38e79efe4de2fbc6d76981e04fb48

Following the instructions in BUILDING.txt, after installing the listed packages and running `qmake -qt=5`, `make` fails with the error `fatal error: QtGui/QAction: No such file or directory #include <QtGui/QAction>`. Running `qmake` without any flags yields the same error.

Is anyone able to verify that building on 14.04 works? If so, can you update the instructions with the full list of packages?

**Comment by SkaveRat** [comment]
Just to confirm: I've got the same problem on `3af01f2`

**Comment by bkconrad** [comment]
I was able to build successfully after purging qt4 packages, reinstalling qt5 again, then checking out the DF2014 branch in this repo:

```
sudo apt-get remove --purge qt4-default qt4-designer qt4-dev-tools qt4-qmake qt4-doc qt4-linguist-tools qtchooser
sudo apt-get install qt5-qmake qt5-default qttools5-dev-tools libqt5script5 libqt5scripttools5 qtscript5-dev
```

Hope that helps, @SkaveRat

**Comment by SkaveRat** [comment]
I've got it to compile a little easier:

on my first try, I was still missing some libs. So there was stuff already generated inside `bin/`, which messed up the compilation on the next tries.

just delete the `bin`directory and it compiles just fine (if you have all dependencies installed).

But: the Makefile is missing a cleanup task ;)

**Comment by splintermind** [comment]
Was that with the makefile_linux?

**Comment by SkaveRat** [comment]
I think it should be the normal Makefile. it gets rewritten by qmake
