### ISSUE TITLE
Failing to connect to DF results in a crash when reconnecting

### ISSUE THREAD

**Issue by splintermind** [splintermind/Dwarf-Therapist#271]
http://www.bay12forums.com/smf/index.php?topic=122968.msg6659906#msg6659906:
If the program fails to connect to DF upon loading, for some reason (such as if I started DT before DF), clicking the Connect button again will instantly close DT, even if the problem has been resolved. 

To reproduce: Open DT with DF not running, close the warning that appears, open DF, open up your fortress in DF, go back to DT, click "Connect to DF". DT exits with no obvious errors. Restart DT; everything's fine. 

Not tested with the "Load Dwarves on Startup" option unchecked, but the same thing happens if I click Refresh then Connect after closing DF.

**Comment by enewton4** [comment]
Is this issue still present after the merge? It works perfectly on my end.

**Comment by splintermind** [comment]
I'd just wanted to test it on windows/linux, but everything seems ok!
