### ISSUE TITLE
Existing custom grid views do not obey changes to "Active Cell" grid color.

### ISSUE THREAD

**Issue by changemewtf** [splintermind/Dwarf-Therapist#273]
**Steps to reproduce**:
1. Go to Options -> Grid Colors and change the "Active Cell" grid color to Red.
2. Copy "Labors Compact" grid view.
3. Go to Options -> Grid Colors and change the "Active Cell" grid color to Cyan.

**What I expected**: All grid views now use cyan for active cells.

**What happened**: Builtin "Labors Compact" grid view uses cyan, but "Labors Compact (COPY)" is still using red.

Making a copy of "Labors Compact (COPY)" reveals that the new copy still uses the old color. (It also exposes another bug where "Labors Compact (COPY)" appears _four_ times in the Grid Views list instead of two, but clicking one and hitting "Remove" results in three disappearing.)

**Comment by splintermind** [comment]
Restarting DT should work-around the cell colors for now. I'll have a permanent fix in the next release.

I haven't been able to get duplicate views to appear though, so if you have any steps to reproduce it let me know.

Thanks for the very detailed report, it made it very easy to track down the cell color problem!

**Comment by changemewtf** [comment]
I couldn't reproduce the duplicate views either. Guess it will continue hiding for now. Glad the report helped. I keep meaning to submit a patch, but until I get around to it, I figure a decent report's better than nothing! I sent a PayPal tip your way, too. Thanks so much for all of your hard work on this.
