### ISSUE TITLE
Dwarf Therapist v34.0.0 is only compatible with DF42.04

### ISSUE THREAD

**Issue by anders-larsson** [splintermind/Dwarf-Therapist#281]
Hello,

I haven't moved to 0.42.04 yet and found that if v34.0.0 is used in combination with 0.42.03 Dwarf Therapist is unable to fetch information regarding units  due to "Bad address" errors.

Using git bisect I found that the changes introduced https://github.com/splintermind/Dwarf-Therapist/commit/b5365dbd0356b6778dd27377e08b67d77709a25e is causing this issue. FYI.

Example:

```
2015-Dec-29 11:36:57.118 INFO   core    FOUND UNIT "0xe5950e70" "Ast Storlutcatten" 2692 20591 [src/dfinstance.cpp:373] (load_dwarves)
2015-Dec-29 11:36:57.118 ERROR  core    READ_RAW: "Bad address" READING 4 BYTES FROM "0xffffffff" TO 0x7ffcd6fd5b50 [src/dfinstancelinux.cpp:167] (read_raw)
2015-Dec-29 11:36:57.118 ERROR  core    READ_RAW: "Bad address" READING 4 BYTES FROM "0x00000003" TO 0x7ffcd6fd5b50 [src/dfinstancelinux.cpp:167] (read_raw)
2015-Dec-29 11:36:57.126 INFO   core    FOUND UNIT "0xe5951bc8" "Ast Uzoluzlir" 2693 20592 [src/dfinstance.cpp:373] (load_dwarves)
2015-Dec-29 11:36:57.126 ERROR  core    READ_RAW: "Bad address" READING 4 BYTES FROM "0xffffffff" TO 0x7ffcd6fd5b50 [src/dfinstancelinux.cpp:167] (read_raw)
2015-Dec-29 11:36:57.126 ERROR  core    READ_RAW: "Bad address" READING 4 BYTES FROM "0x00000003" TO 0x7ffcd6fd5b50 [src/dfinstancelinux.cpp:167] (read_raw)
```

**Comment by anders-larsson** [comment]
It works perfectly fine in 0.42.04 though. I guess it's a matter of stance on backwards compatibility.

**Comment by splintermind** [comment]
Yes I'm aware of this and I made notes about it on dffd and on the forums that it's specifically for 42.04 until the older layouts can be updated.

If I can find time I'll see about updating to support 42.03.
