### ISSUE TITLE
Linux build failing

### ISSUE THREAD

**Issue by baudren** [splintermind/Dwarf-Therapist#285]
On Linux Mint 17 (based on Ubuntu 14.04), after the `qmake` command (tried both with `qt5` and `qt4`, the `make` instruction fails after a while with this output:

```
g++ ... release/.moc/moc_activityevent.cpp
[ -d doc ] || mkdir doc; TEXINPUTS=.:/home/benjamin/Documents/My Games/python-lnp/LNP/Utilities/Dwarf-Therapist/doc/images: pdflatex -output-directory=doc "/home/benjamin/Documents/My Games/python-lnp/LNP/Utilities/Dwarf-Therapist/doc/Dwarf Therapist.tex"
/bin/sh: 1: Games/python-lnp/LNP/Utilities/Dwarf-Therapist/doc/images:: not found
make[1]: *** [doc/Dwarf Therapist.pdf] Error 127
```

Any idea what is going on there? The folder `doc/images` exists, and contains a bunch of png files already (125). Thanks in advance,

**Comment by Couchmonster** [comment]
You got an unescaped space character cutting to Games folder. Never use
space in folder names.
Am 02.01.2016 4:39 nachm. schrieb "Benjamin Audren" <
notifications@github.com>:

**Comment by txtsd** [comment]
@Couchmonster That's just a best practice rule, not a requirement.

The build system should handle the escaping or stick the path in quotes.

**Comment by Hello71** [comment]
qmake sucks. quotes magically disappear. try `sed -i -e '104s/="/=\"/;104s/:"/:\"/ dwarftherapist.pro`.

**Comment by baudren** [comment]
gosh, thanks, I did not realise. I am still dreaming of a day where spaces will live happily in our paths, but I guess it is still not today :) Thanks for the awesome work, by the way!
