### ISSUE TITLE
All dwarves show "Labor cannot be changed for non-citizens"

### ISSUE THREAD

**Issue by ccaviness** [splintermind/Dwarf-Therapist#287]
I'm running DF 0.42.04 and DT 34.0.0 on OS X 10.11.2.

I'm getting back into the DF groove after a couple of years away. I've got DF and DT set up and running, but I can't use DT to toggle labors.

All dwarves show "Labor cannot be changed for non-citizens":
![screenshot](https://lh3.googleusercontent.com/0hwGlHyFiqIqlM8RZAlb1A5wco_gPqJ_4tVdTB6u6hfeTT4D0g8H--kmiY9BtoqtHIhP65fr1aIvy1qufyR1DTGBwxz_2RpYD7sZdwGBvMWsLZ1_FPzEpZ5XabcW5hLXDCBj6Ha8iInp8_i3YRlh4KvnmpyyC8xvsaXX_ihPe_qJJBU4vLft2x_TIskbWwLb0LvechOnacWrCW4Enp5URzjwfgssU7jUUoKIBG6SmMbV2PY8hNHpVQYrv7R9dyNxCIEyRiLE4SKKPBTI4fd8wuPiIsq7pJASiQC5fzHW4LDwYQP4bffvVAJjcbD_5F0pTadNd81wNrreuSd4a0Pd6OmG2tB0hPtRn2j3bJ_svED8dDu-M0jdkAx-R5nDCLEv0cpWT5E8MhkVxr32Yty2bedrHtqDJAGyoi6fdMZdZEJvYf5OVdlFwMI7xmKriNqvKz1MN1R9F3nRVpTaHGMIgaZIlne0y_2DKejLKzdauPfML1eyPWMN-saFf6tCPrLRy-4tUdUyvTfF-KZZ5K3iFp7NKwZLEBX4DnQsAGKqC2Uaif6_7bANN2Y_b4qsZL4hWzhfTA=w1190-h646-no)

I tried swapping in the latest memory layout from a387db7448f4df71fb3e839f363688143325dcf7, but DT crashes on startup with that one.

**Comment by enewton4** [comment]
Are you sure that you are running 0.42.04? I had this exactly same problem when using the latest DT with 0.42.03 DF. The problem was fixed after upgrading to 0.42.04. If all else fails you might want to try building it yourself from HEAD.

**Comment by ccaviness** [comment]
Yep, double-verified I'm running v0.42.0.4.

I'll try building it.

**Comment by splintermind** [comment]
This is definitely a problem with DT 34.0 and 42.04. Fricy reported the same issues. The memory layout you referenced is the one you want, just build from HEAD as Numerius suggested.

**Comment by ccaviness** [comment]
Seems to be fixed in HEAD. Thanks.
