### ISSUE TITLE
Crashes with 42.04 when clicking certain dwarves

### ISSUE THREAD

**Issue by Waladil** [splintermind/Dwarf-Therapist#288]
When clicking certain dwarves (either their name or any of their skills to activate/deactivate them,) DT stops responding and is closed by Windows. It is happening with two dwarves out of my 22, and I cannot find any correlation between the two, except that they came in the same migration wave.

I can still assign/unassign labors to those dwarves, by using assignment commands that don't involve literally clicking on either of them. For example, I can click on the one above a bugged dwarf, shift-click the one below the bugged dwarf, and assign a labor to all three, then remove it from the two neighbors.

Attached is a copy of my save: https://www.dropbox.com/s/qlse2uuzl733l1p/WaladilDTBugSave.zip?dl=0

Using DT version 32.0.0 with memory layouts downloaded from Github on appr. Jan 3rd 2016.

EDIT: Forgot an important detail. The bugged dwarves are Kogan Adassazir, the female doctor, and Ustuth Udosunib, the male Omni-dwarf (peasant).

**Comment by splintermind** [comment]
Version 32 is intended for DF up to 40.24. Please update to the latest DT which is intended to support DF 42.03-42.04.

Edit: Just tested the save with DT 35 and it seems it should resolve the problem.

**Comment by Waladil** [comment]
It took me a while to find out HOW to get v.35. The link on the front page of the github still goes to the v.32 download page. I didn't even know there was a newer version available until you said so just now.

But downloaded now, and yep it does fix it.
