### ISSUE TITLE
Support DF version 42.06.

### ISSUE THREAD

**Issue by eaburns** [splintermind/Dwarf-Therapist#295]
I can't connect to dwarf fortress version 42.06. It says that the latest supported version is 42.05.

**Comment by eaburns** [comment]
Did I do something wrong posting this here?

**Comment by MEXAHOTABOP** [comment]
you already answer on own question 
just wait for new memory layouts

**Comment by eaburns** [comment]
How so? Sorry if I'm not familiar with the protocol, but a single sentence of explanation would be more helpful than snark.

**Comment by insolor** [comment]
@eaburns, obviously, it says that DF 0.42.06 is not supported because DF 0.42.06 is not supported (yet).

**Comment by eaburns** [comment]
I never claimed that it wasn't a _known_ issue, but it seems like an issue nonetheless. Most projects have tracking bugs for known issues so that folks can follow the progress. Obviously this isn't one of them. Sorry for the bother. Rest assured I'll never bother you by opeing an issue here again.

**Comment by insolor** [comment]
@eaburns we all are waiting for the new version of the utility. But it depends much on another projects progress (DF structure memory layout reverse engineering, in particular). The author of the utility just not able to fix this at the time.
Excuse us for a cold shoulder.

**Comment by eaburns** [comment]
Actually, it's my fault. My email didn't show the second sentence of @MEXAHOTABOP's initial response so it came off as being quite rude when in fact it wasn't. Sorry.

**Comment by splintermind** [comment]
There are already layouts posted on the DF forums for linux and windows if you're comfortable manually adding them.

Releases will be out soon.
