### ISSUE TITLE
Equipment overview doesn't display missing uniform items.

### ISSUE THREAD

**Issue by ghost** [splintermind/Dwarf-Therapist#299]
Displays N/A no matter what I do.

**Comment by splintermind** [comment]
What O/S and what version of DF?

**Comment by sv-esk** [comment]
v37(0.42.06) linux. Same thing.
![dt3](https://cloud.githubusercontent.com/assets/6759752/13555225/83d0221e-e3c3-11e5-9896-8d8609b6633d.png)

**Comment by ghost** [comment]
I am on Windows 10 x64 and I am using the cutting edge starter pack, which is 42.06. Autolabor is properly disabled.

**Comment by splintermind** [comment]
I haven't been able to reproduce this yet, can someone upload a save I can take a look at?

Note that the equipment overview is specifically for displaying worn/tattered items only. Does the equipment column show wear on items?

**Comment by ghost** [comment]
If it's for worn/tattered items only then it's probably working. I checked the manual and I saw no mention of this.

**Comment by sv-esk** [comment]
It shows civilian worn/missing items, but does not show military and civilian job uniform missing items

**Comment by splintermind** [comment]
Yeah it was never intended to display missing uniform items, but adding that would make the overview more intuitive. Especially if it's not explained in the manual.
