### ISSUE TITLE
pdflatex is not listed on dependencies list in BUILDING.rst

### ISSUE THREAD

**Issue by nikow** [splintermind/Dwarf-Therapist#301]
It looks like, pdflatex should be listed on dependencies in linux. To install it you need (on ubuntu) call `sudo apt-get install texlive-latex-base`

```
nikow@nimira-X550LC:/tmp/Dwarf-Therapist$ qmake -qt=5
Project MESSAGE: Setting up for Qt 5
Project MESSAGE: Setting up for Qt 5
Project MESSAGE: Setting up for Linux
Checking for pdflatex... not found
Project MESSAGE: Setting up for Qt 5
Project MESSAGE: Setting up for Linux
Checking for pdflatex... not found
nikow@nimira-X550LC:/tmp/Dwarf-Therapist$
```

**Comment by Hello71** [comment]
better to make patch for project to note that it is warning.

edit: that didn't make sense. best make a patch for `dwarftherapist.pro` that changes "not found" to "not found\nManual will not be built.".
