### ISSUE TITLE
Disabling global weights of multiple categories leads to roles reporting 0 vs 50%

### ISSUE THREAD

**Issue by thistleknot** [splintermind/Dwarf-Therapist#31]
If I say, disable all weights but skill, or preferences.  Roles that don't have any defined skills [or peferences, depending on scenario] will report 0% when they should report 50%.

50% means neither good nor bad,  Labelling all dwarf's for a role as 0% because the role has nothing defined to give it a value (aka preferences or skills, depending on scenario), means that roles that do have preferences defined, but 0 matches are found, will lead to a higher % reported for those roles (0 values are padded due to the way skewed distributions are handled)  than roles that do not have any preferences defined

**Comment by splintermind** [comment]
It may be very misleading to players who don't know what's going in the back-end to see that everyone has a 50% rating of nothing. Suddenly zero isn't zero, it's 50.

**Comment by thistleknot** [comment]
"Suddenly zero isn't zero, it's 50."  it's not 0 though. What this 0 is, is a lack of anything defined in a role, not [what 0 should mean] being at the minimum scale of what was defined in the role.

 50% should mean neutral (that's why we always average around .5 mean for each distribution before combining them using weighted averages).  So if a role doesn't define any categories we can value, then 50% should be used, as this is our neutral center, because <50% means undesirable, and we're not saying these dwarf's are undesirable because the role doesn't define anything.  In other words, if there is nothing to be defined to be bad or good, everyone's 50%.  

Seeing 0 means a dwarf is undesirable (the worst) for the job, that's not the case in this situation, it just means 0 is being reported for the entire ROLE (note the distinction hear, priests are 0 for a lot of roles, but in this case it's the role that is all 0) which SHOULDN'T mean the dwarf is bad for the job, just that he is neither good nor bad (aka 50%) based on the roles definition.

0 is one thing for priests who can't learn skills, but saying a whole role and all ddwarf's in that role = 0% = same thing as priest is misleading.  Instead of 0 or 50, I would recommend highlighting the role at a minimum so a player can see that the reason the role is reporting whatever % (0 or 50) is due to what's lacking definition in the role (such as if it's missing preferences)

the problem becomes most profound if a player wants to base a labor optimization plan on one category.   Say a player wanted an attributes only weight, then any role that doesn't have attributes is reported as 0%, which means they would be rated lower than truly bad fits for attribute roles (aka <50%).
