### ISSUE TITLE
Ability to Sort Animals by Caste

### ISSUE THREAD

**Issue by endofzero** [splintermind/Dwarf-Therapist#34]
Enhancement:
Include the ability to sort the animal list by caste.
This would help make it easier to butch and worry less about killing off your last mating pair.

**Comment by splintermind** [comment]
Is the grouping by race/caste insufficient for this?

**Comment by endofzero** [comment]
Group by is sufficient, overlooked the feature.

**Comment by splintermind** [comment]
I usually group by race, and then sort by age to ensure I'm butchering the oldest.
