### ISSUE TITLE
OSX crashes after admin pwd

### ISSUE THREAD

**Issue by splintermind** [splintermind/Dwarf-Therapist#4]
[Happens after DT asks for the admin password.](http://www.bay12forums.com/smf/index.php?topic=122968.msg5009253#msg5009253)

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
objc[5970]: garbage collection is OFF
**\* error for object 0x1003a7d70: pointer being freed was not allocated

**Comment by tareqak** [comment]
This happens after using the macdeployqt tool to make a dmg file. I'm looking at what I can do to fix it.

**Comment by tareqak** [comment]
I passed in a different set of arguments to macdeployqt and it seems to work for me now.
