### ISSUE TITLE
Script window's help information isn't read-only and is outdated

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#41]
If you click on the reference pane in the filter script definition window you can add, subtract, delete, and add characters---basically anything you can expect to do with a standard TXT file you can do in the pane, and the changes seem to persist. I don't think this is intentional behavior.
- [x] Set script help information to read-only
- [x] Update script help information with recently added functions

**Comment by splintermind** [comment]
Yeah the editing is harmless, it's only saved for the current session. Nevertheless, still a bug.
