### ISSUE TITLE
Windows: Building with QT creator per Building.txt fails

### ISSUE THREAD

**Issue by nonymous** [splintermind/Dwarf-Therapist#42]
I tried to build the project in Windows 7 AMD64, following the directions in Building.txt, it failed:

jom: C:\Users########\Documents\GitHub\build-dwarftherapist-Desktop_Qt_5_3_MSVC2013_64bit-Debug\Makefile [debug] Error 2
12:21:38: The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project dwarftherapist (kit: Desktop Qt 5.3 MSVC2013 64bit)
When executing step 'Make'
12:21:38: Elapsed time: 01:35.

**Comment by nonymous** [comment]
those instructions aren't very big on detail:
"Instructions for how to build from source are as follows:

For Windows, download the QTCreator IDE and open the dwarftherapist.pro file.  You can build
from within QTCreator."

**Comment by splintermind** [comment]
Do your other projects build properly? Are you sure this is a DT issue and not a QT configuration problem?

**Comment by nonymous** [comment]
This is the only project I have using QT, but I just installed it.  Maybe there was some configuration change I needed to make?

**Comment by splintermind** [comment]
Hrmm I really can't say. The last time I built it with MSVC was a long time
ago. It's a hassle but you could try the mingw package instead.

On Mon, Jul 28, 2014 at 8:34 PM, nonymous notifications@github.com wrote:

> This is the only project I have using QT, but I just installed it. Maybe
> there was some configuration change I needed to make?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/splintermind/Dwarf-Therapist/issues/42#issuecomment-50379164
> .

## 

-josh

--my divinity is caught between the colors of a butterfly--

**Comment by Hello71** [comment]
paste the _entire_ output of the build
