### ISSUE TITLE
Add a "Professions" option to the Super Labor creation window

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#44]
Currently when you want to assign a super labor which parallels a profession, you have to manually select the jobs in that super labor. It would be helpful to add a Profession drop-down in this window: when you select a profession in the drop-down, the correct jobs are automatically toggled on, and the others are toggled off. This would save on the effort required in assigning jobs twices.

**Comment by splintermind** [comment]
When you mention professions, are you meaning custom professions?

**Comment by ResidentMario** [comment]
Yes. Specifically, I had to enable all of the hauling labors individually, twice, in underwriting the roles and labors behind my military recruitment view---very inconvenient.

**Comment by splintermind** [comment]
I don't follow what you're doing here. You can create either a super labor or a custom profession from a specific dwarf. That should already set all the labors in the editor. Why did you have to create both a super labor and a custom profession column?

**Comment by ResidentMario** [comment]
Hmm. Yes, it appears that if you are writing both professions and labors at the same time you can circumvent the issue by setting a dwarf to a profession, creating the super-labor from that profession, and then clearing changes. I'll close this issue as niche, then.

**Comment by splintermind** [comment]
Alternatively, I could add another menu item to the custom professions in the dock, to 'Create a super labor from this custom profession' or some such option. I honestly didn't expect people to want both a custom profession and a super labor that were identical (other than the custom profession).

Another option could be to have a way to toggle only the labors in a custom profession cell, for example, shift clicking only toggles labors, but simply left clicking both toggles labors and the custom profession.

**Comment by ResidentMario** [comment]
I'd focus on other stuff for now and come back to this later.

Edit: Aha! I see. There is, indeed, no reason to define a super-labor matching a custom profession---I didn't notice the custom profession option in the view dropdown!

Oh man, how stupid of me.

Never mind.
