### ISSUE TITLE
What about two-handed wielding?

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#51]
A quick look at the two-handed sword column in the military view finds this:

http://i.imgur.com/4jKUfbE.png

It's not quite right to say that they can't wield the weapon, rather that they can't wield it in one hand. Besides, two-handed swords are multigrasp---you don't want to wield them in one hand anyway.

**Comment by splintermind** [comment]
It was (still is as far as I'm aware) broken in DF where their actual body size isn't used to determine weapon usage but instead the default 60,000 is checked.

Until that's fixed there's a bit of a disconnect between the unit's real size, and the size that's used to determine if a weapon is usable, which is what you're seeing.

**Comment by ResidentMario** [comment]
Here's the tracker issue: http://www.bay12games.com/dwarves/mantisbt/view.php?id=0005812.

Maybe hide the dwarf's body size in the tooltip, for now, so as not to give the user conflicting information until this is fixed?

Interestingly, I mention this bug in a footnote much earlier in the guide.

Edit: There isn't really an elegant solution to this and it's not really important, so I'm closing the issue.
