### ISSUE TITLE
Additional labor gradient for super-labors.

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#52]
When a dwarf has almost, but not quite, all of the labors in a super-labor column enabled, the column is filled in in a manner that is synonymous to the "all labors enabled" one, which is misleading. You should introduce another in-between color for when a lot but not all labors are enabled, and leave the fully colored-in box for fully enabled super-labors.

Screencap of what I mean:

http://i.imgur.com/x36eNA4.png

**Comment by splintermind** [comment]
It actually scales the gradient based on enabled / total labors. The issue is that with so many labors, a gradient of 8/10 vs 9/10 becomes indiscernible.

**Comment by ResidentMario** [comment]
It'd be best to cap the gradient to a certain top easily discernible from the "all enabled" fill, then.

**Comment by splintermind** [comment]
Yeah I'm trying that now. The same has already been done for the low end to ensure it's still slightly visible if at least one is enabled.

**Comment by splintermind** [comment]
This should be better with the last release.
