### ISSUE TITLE
Enhancements to the behavior of "Armor" columns

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#54]
I'm a little confused by what these options are meant to achieve. The "Equipment" column you've added to the views should handle clothing concerns just fine: these columns should be reserved for telling you whether or not your dwarves have armor armor equipped, ae. breastplates, greaves, etc. etc.

**Comment by splintermind** [comment]
Isn't that exactly what they do? They show a red indicator, the larger indicating the more items/equipment that are missing. The only similarity with the general equipment column is that they also show wear with the border.

**Comment by ResidentMario** [comment]
I see, this is an issue with the fort I imported from another player. He has dwarves training in a danger room without anything but their clothes on! No wonder two of them are permanently disabled and lying in the infirmary. I assumed they had some sort of armor on---alright, my error, closing this then.
