### ISSUE TITLE
Change "Column" to "Columns" in the custom grid view definition window's column definitions

### ISSUE THREAD

**Issue by ResidentMario** [splintermind/Dwarf-Therapist#55]
Some are "column", some are "columns". Clearly the latter is better since you have many choices.

**Comment by splintermind** [comment]
I intend to remove the 'column(s)' suffix entirely, as it's already fairly obvious those are columns you're adding to the view.

**Comment by ResidentMario** [comment]
Remove the "Add" in "Add Trait Column" and "Add Weapon Column" too, then.
