### ISSUE TITLE
QtWidgets: No such file or directory 

### ISSUE THREAD

**Issue by Jay-Roden** [splintermind/Dwarf-Therapist#60]
[James@localhost Dwarf-Therapist-master]$ make
/usr/lib/qt4/bin/qmake -o Makefile dwarftherapist.pro
Project MESSAGE: Release Mode
Project MESSAGE: Setting up for Linux
Project MESSAGE: Setting up for Linux Install
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtScript -I/usr/include -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/dfinstancelinux.o src/dfinstancelinux.cpp
src/dfinstancelinux.cpp:23:21: fatal error: QtWidgets: No such file or directory
 #include <QtWidgets>
                     ^
compilation terminated.
make: **\* [bin/release/dfinstancelinux.o] Error 1

I have been at this for hours and i still can't get it to work.

**Comment by anders-larsson** [comment]
Dwarf Therapist is a qt5 application. You're trying to build it with qt4.

**Comment by Jay-Roden** [comment]
I have tried installing qt5 but it won't install it keeps installing qt4.

**Comment by anders-larsson** [comment]
Not sure where qt5 is located for you, but for me it is located in /usr/lib/qt5/.
Do the following steps:

```
make clean
/usr/lib/qt5/bin/qmake
make
...
```

**Comment by Jay-Roden** [comment]
No such file or directory

**Comment by Jay-Roden** [comment]
I just downloaded qt5-qtbase-5.3.1-5.fc20.i686.rpm and it told me it was already instlalled

**Comment by anders-larsson** [comment]
If you run 'rpm -qlp path/to/qt5-qtbase-5.3.1-5.fc20.i686.rpm' it should tell you all files included in qt5-qtbase. That might help you find qt5's qmake command.

**Comment by Jay-Roden** [comment]
Weirdly i don't see qmake in the rpm

/etc/xdg/qtchooser
/etc/xdg/qtchooser/default.conf
/etc/xdg/qtchooser/qt5-32.conf
/etc/xdg/qtchooser/qt5.conf
/usr/lib/libQt5Concurrent.so.5
/usr/lib/libQt5Concurrent.so.5.3
/usr/lib/libQt5Concurrent.so.5.3.1
/usr/lib/libQt5Core.so.5
/usr/lib/libQt5Core.so.5.3
/usr/lib/libQt5Core.so.5.3.1
/usr/lib/libQt5DBus.so.5
/usr/lib/libQt5DBus.so.5.3
/usr/lib/libQt5DBus.so.5.3.1
/usr/lib/libQt5Network.so.5
/usr/lib/libQt5Network.so.5.3
/usr/lib/libQt5Network.so.5.3.1
/usr/lib/libQt5Sql.so.5
/usr/lib/libQt5Sql.so.5.3
/usr/lib/libQt5Sql.so.5.3.1
/usr/lib/libQt5Test.so.5
/usr/lib/libQt5Test.so.5.3
/usr/lib/libQt5Test.so.5.3.1
/usr/lib/libQt5Xml.so.5
/usr/lib/libQt5Xml.so.5.3
/usr/lib/libQt5Xml.so.5.3.1
/usr/lib/qt5
/usr/lib/qt5/imports
/usr/lib/qt5/libexec
/usr/lib/qt5/plugins
/usr/lib/qt5/plugins/accessible
/usr/lib/qt5/plugins/bearer
/usr/lib/qt5/plugins/bearer/libqconnmanbearer.so
/usr/lib/qt5/plugins/bearer/libqgenericbearer.so
/usr/lib/qt5/plugins/bearer/libqnmbearer.so
/usr/lib/qt5/plugins/generic
/usr/lib/qt5/plugins/imageformats
/usr/lib/qt5/plugins/platforminputcontexts
/usr/lib/qt5/plugins/platforms
/usr/lib/qt5/plugins/platformthemes
/usr/lib/qt5/plugins/printsupport
/usr/lib/qt5/plugins/sqldrivers
/usr/lib/qt5/plugins/sqldrivers/libqsqlite.so
/usr/share/doc/qt5
/usr/share/doc/qt5-qtbase
/usr/share/doc/qt5-qtbase/LGPL_EXCEPTION.txt
/usr/share/doc/qt5-qtbase/LICENSE.GPL
/usr/share/doc/qt5-qtbase/LICENSE.LGPL
/usr/share/doc/qt5/global
/usr/share/doc/qt5/global/compat.qdocconf
/usr/share/doc/qt5/global/config.qdocconf
/usr/share/doc/qt5/global/externalsites
/usr/share/doc/qt5/global/externalsites/external-resources.qdoc
/usr/share/doc/qt5/global/externalsites/qch-urls.qdoc
/usr/share/doc/qt5/global/externalsites/qt-webpages.qdoc
/usr/share/doc/qt5/global/externalsites/qtcreator.qdoc
/usr/share/doc/qt5/global/externalsites/rfc.qdoc
/usr/share/doc/qt5/global/fileextensions.qdocconf
/usr/share/doc/qt5/global/html-config.qdocconf
/usr/share/doc/qt5/global/html-footer.qdocconf
/usr/share/doc/qt5/global/html-header-offline.qdocconf
/usr/share/doc/qt5/global/html-header-online.qdocconf
/usr/share/doc/qt5/global/includes
/usr/share/doc/qt5/global/includes/examples-run.qdocinc
/usr/share/doc/qt5/global/macros.qdocconf
/usr/share/doc/qt5/global/manifest-meta.qdocconf
/usr/share/doc/qt5/global/qt-cpp-defines.qdocconf
/usr/share/doc/qt5/global/qt-html-templates-offline.qdocconf
/usr/share/doc/qt5/global/qt-html-templates-online.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults-offline.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults-online.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults.qdocconf
/usr/share/doc/qt5/global/template
/usr/share/doc/qt5/global/template/images
/usr/share/doc/qt5/global/template/images/Qt-dark_gradient.png
/usr/share/doc/qt5/global/template/images/Qt-footer-bg.jpg
/usr/share/doc/qt5/global/template/images/Qt-footer_shadow.png
/usr/share/doc/qt5/global/template/images/Qt-gradient.png
/usr/share/doc/qt5/global/template/images/Qt-header-bg.jpg
/usr/share/doc/qt5/global/template/images/Qt-logo.png
/usr/share/doc/qt5/global/template/images/arrow.png
/usr/share/doc/qt5/global/template/images/arrow_bc.png
/usr/share/doc/qt5/global/template/images/arrow_down.png
/usr/share/doc/qt5/global/template/images/bg_l.png
/usr/share/doc/qt5/global/template/images/bg_l_blank.png
/usr/share/doc/qt5/global/template/images/bg_ll_blank.png
/usr/share/doc/qt5/global/template/images/bg_r.png
/usr/share/doc/qt5/global/template/images/bg_ul_blank.png
/usr/share/doc/qt5/global/template/images/bgrContent.png
/usr/share/doc/qt5/global/template/images/blu_dot.png
/usr/share/doc/qt5/global/template/images/box_bg.png
/usr/share/doc/qt5/global/template/images/breadcrumb.png
/usr/share/doc/qt5/global/template/images/btn_next.png
/usr/share/doc/qt5/global/template/images/btn_prev.png
/usr/share/doc/qt5/global/template/images/bullet_dn.png
/usr/share/doc/qt5/global/template/images/bullet_gt.png
/usr/share/doc/qt5/global/template/images/bullet_sq.png
/usr/share/doc/qt5/global/template/images/bullet_up.png
/usr/share/doc/qt5/global/template/images/feedbackground.png
/usr/share/doc/qt5/global/template/images/header_bg.png
/usr/share/doc/qt5/global/template/images/home.png
/usr/share/doc/qt5/global/template/images/horBar.png
/usr/share/doc/qt5/global/template/images/ico_note.png
/usr/share/doc/qt5/global/template/images/ico_note_attention.png
/usr/share/doc/qt5/global/template/images/ico_out.png
/usr/share/doc/qt5/global/template/images/logo.png
/usr/share/doc/qt5/global/template/images/page.png
/usr/share/doc/qt5/global/template/images/page_bg.png
/usr/share/doc/qt5/global/template/images/spinner.gif
/usr/share/doc/qt5/global/template/images/sprites-combined.png
/usr/share/doc/qt5/global/template/style
/usr/share/doc/qt5/global/template/style/offline.css
/usr/share/doc/qt5/global/template/style/online.css
/usr/share/qt5
/usr/share/qt5/translations

**Comment by anders-larsson** [comment]
I see you're running a RPM-based Linux distribution.
You probably need to install a devel package. It seems like there exists a qt5-qtbase-devel package.

**Comment by Jay-Roden** [comment]
It says i already have it installed

**Comment by anders-larsson** [comment]
Run 'rpm -qlp' on that package in and see if qmake is included.

**Comment by anders-larsson** [comment]
http://forums.opensuse.org/showthread.php/492450-Installed-Qt5-Creator-Qt5-Qmake-missing
" You need to install libqt5-qtbase-devel which contains qmake-qt5". Perhaps useful if you're running opensuse.

**Comment by Jay-Roden** [comment]
I am running the Fedora distribution.

**Comment by Jay-Roden** [comment]
when i try "sudo yum erase qt5-qtbase-devel.i686" it says it's not there but when i try "yum search qt5" it says it's there

**Comment by vwood** [comment]
Not all versions of all distros have qt5 packages available. It's a bit crap to require it to be honest.

**Comment by splintermind** [comment]
Which version of QT does every distro have?

**Comment by Tolbin** [comment]
According to distrowatch (if I'm using it correctly) most distros have QT4. A few others seem to have QT5 available, among them Ubuntu.

http://distrowatch.com/search.php?pkg=qt&pkgver=4#pkgsearch
http://distrowatch.com/search.php?pkg=qt&pkgver=5#pkgsearch

**Comment by Hello71** [comment]
nothing to be done here, close?
