### ISSUE TITLE
filter dwarfs by age

### ISSUE THREAD

**Issue by wookietreiber** [splintermind/Dwarf-Therapist#64]
I would like the ability to filter dwarfs by age. When I am assigning labors, I do not want to train dwarfes older than some age, so when they die of old age, the experience they gained will be lost. I think, this will be generally useful.

**Comment by splintermind** [comment]
You can write a filter script <code>d.get_age() < 100</code>, or right click on the first column (with the names), and sort by age, or group by age. I'm not sure what more you want.

**Comment by wookietreiber** [comment]
I believe this is missing from the edit filter script help text. I have just updated to HEAD and looked over it twice now and could not find it. Or maybe I am blind...

**Comment by splintermind** [comment]
[It's there](https://github.com/splintermind/Dwarf-Therapist/blob/master/inc/dwarf.h#L195) but it may not be documented in the script help window as per #41.
