### ISSUE TITLE
 Segmentation fault on connect to DF.

### ISSUE THREAD

**Issue by kiryl** [splintermind/Dwarf-Therapist#69]
Built from commit 5af43c14949f.

Core was generated by `bin/release/DwarfTherapist'.
Program terminated with signal SIGSEGV, Segmentation fault.
0  0x00000000006175e9 in UnitHealth::add_info(eHealth::H_INFO, bool, bool, bool, bool) ()
(gdb) bt
0  0x00000000006175e9 in UnitHealth::add_info(eHealth::H_INFO, bool, bool, bool, bool) ()
1  0x0000000000618f7c in UnitHealth::read_health_info() ()
2  0x000000000061c5fb in UnitHealth::UnitHealth(DFInstance_, Dwarf_, bool) ()
3  0x00000000005209ee in Dwarf::refresh_data() ()
4  0x0000000000521f29 in Dwarf::Dwarf(DFInstance_, unsigned int const&, QObject_) ()
5  0x000000000052359b in Dwarf::get_dwarf(DFInstance_, unsigned int const&) ()
6  0x00000000005509d1 in DFInstance::load_dwarves() ()
7  0x000000000056a254 in DwarfModel::load_dwarves() ()
8  0x00000000004a9f4a in MainWindow::read_dwarves() ()
9  0x00000000004abee8 in MainWindow::connect_to_df() ()
10 0x000000000065975c in MainWindow::qt_static_metacall(QObject_, QMetaObject::Call, int, void*_) ()
11 0x00007f80ab15013a in QObject::event(QEvent_) () from /usr/lib/libQt5Core.so.5
12 0x00007f80ac2a8897 in QWidget::event(QEvent_) () from /usr/lib/libQt5Widgets.so.5
13 0x00007f80ac3c11ab in QMainWindow::event(QEvent_) () from /usr/lib/libQt5Widgets.so.5
14 0x00007f80ac26a15c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/libQt5Widgets.so.5
15 0x00007f80ac26f6ee in QApplication::notify(QObject_, QEvent_) () from /usr/lib/libQt5Widgets.so.5
16 0x00007f80ab120aeb in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib/libQt5Core.so.5
17 0x00007f80ab122ab3 in QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData_) () from /usr/lib/libQt5Core.so.5
18 0x00007f80ab177ad3 in ?? () from /usr/lib/libQt5Core.so.5
19 0x00007f80a9b92b84 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
20 0x00007f80a9b92dc8 in ?? () from /usr/lib/libglib-2.0.so.0
21 0x00007f80a9b92e6c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
22 0x00007f80ab177ec7 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) ()
   from /usr/lib/libQt5Core.so.5
23 0x00007f80ab11e512 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/libQt5Core.so.5
24 0x00007f80ab125ecc in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
25 0x000000000042780b in main ()

**Comment by splintermind** [comment]
Do you still have the save that caused this?

**Comment by kiryl** [comment]
It happens on any save for me. But only on release builds.

I don't have time to debug if myself currently :-/

**Comment by splintermind** [comment]
Maybe you're using an old game_data.ini without the <code>[health_info]</code> section?

**Comment by kiryl** [comment]
Ouch. game_data.ini was not found to bug on my side. With correct game_data.ini it works fine.

Anyway SIGSEGV is not right response on missing or broken game_data.ini. Worth fixing from my POV.

**Comment by splintermind** [comment]
Yeah for sure. I'll look at it when I get a chance now that I know how to reproduce it.
