### ISSUE TITLE
Dwarf Therapist relies too much on the current directory

### ISSUE THREAD

**Issue by Hello71** [splintermind/Dwarf-Therapist#72]
currently known instances:
- game_data.ini, memorylayouts (#30)
- log/log.txt

the former should probably be moved to /etc, the latter should just print to stderr on *nix systems (or preferably all systems)

**Comment by Cerbsen** [comment]
But mind, LNP relies on the relative path and the ability for a "standalone" installation.

**Comment by Hello71** [comment]
qcoreapplication::getapplicationdir()

**Comment by Hello71** [comment]
done a patch, just need to split these changes up into separate commits. that'll wait till tomorrow though.

**Comment by Hello71** [comment]
closed in favor of #30 and #114.
