### ISSUE TITLE
use process_vm_readv and process_vm_writev instead of ptrace and opening /proc/mem

### ISSUE THREAD

**Issue by Hello71** [splintermind/Dwarf-Therapist#73]
the former requires Linux 3.2 and 2.15 according to the man page, but afaict "backwards compatibility" is not a major concern here; case in point: qt5.

I figure there's some sensible way of checking for older kernels and falling back to ptrace.

**Comment by Hello71** [comment]
oh, and the obvious benefit of process_vm_writev is that ptrace doesn't have to be called a bajillion times to write anything -- not that that really helps because of #71

**Comment by Hello71** [comment]
if using process_vm_writev might as well use _readv too.

**Comment by Hello71** [comment]
these changes approximately halve the time required to complete a read, going from >5 seconds to around 2 seconds for a dwarven read.

unfortunately, DT seems to spend a good deal of time reading invalid memory:

```
bin/release/DwarfTherapist: error reading 4 bytes from 0xc to 0x2d73248: Bad address
bin/release/DwarfTherapist: error reading 4 bytes from 0x44 to 0x24f3d98: Bad address
bin/release/DwarfTherapist: error reading 256 bytes from (nil) to 0x24f4168: Bad address
```

and things like that.

note that I am compiling DT as 64-bit, so maybe that has to do with something.

**Comment by Hello71** [comment]
since I can't just use `time`, looking at the clock seems to show results of around 3.5 seconds to load with process_vm_readv and around 8 seconds to load with ptrace; iow, the difference between "waiting for it to load..." and "meh alt-tab".

**Comment by Hello71** [comment]
gentoo's qt overlay doesn't have multilib qt5. could you pull that in and test it with `CXXFLAGS=-m32 LDFLAGS=-m32`? if it doesn't spew errors, it probably works fine.

**Comment by Hello71** [comment]
also, this doesn't negate the need to have ptrace permission since the p_vm syscalls check for that in the kernel (through lsms if applied)

**Comment by Hello71** [comment]
fwiw, these invalid reads happened before, it's just that they never printed errors.

**Comment by splintermind** [comment]
I had a chance to test this a bit today. Nothing exploded, but as you've mentioned a lot of <code>EFAULT</code> errors showing up. Checking the addresses prior to the raw reads with <code>is_valid_address</code> reduces the spam considerably though.

I haven't been able to investigate the remaining bad addresses due to some debugging symbol problems I have to resolve first.

**Comment by Hello71** [comment]
> Checking the addresses prior to the raw reads with `is_valid_address`

why is this necessary in the first place?

**Comment by splintermind** [comment]
I don't know that it is necessary, I was just reporting my findings. That check changing the results indicates that there's something happening with the pages read and/or the offsets used to read the values.

**Comment by splintermind** [comment]
The last commit helps further with the 'bad address' errors being thrown, however there's still something strange going on.

There was a single dwarf language word: <code>[T_WORD:BATTLE:nokzam]</code> which resulted in a bad address. Retyping the line in the raw file resolved the error.

Another cause was the description of the Echidna creature. Removing the double space in the description resolved that error as well.

This brought the errors down to only two for the state names of <code>WATER</code> and <code>GLASS_CLEAR</code> materials.

**Comment by splintermind** [comment]
Well I'm pretty stumped with these bad addresses. Seems it's a different set of strings each time, but I'm unable to duplicate it on windows. Maybe it's a vmware problem?

Hello71, have you had a chance to test it with the last commits for the materials/word fixes?

**Comment by Hello71** [comment]
Been on vacation from vacation. I don't get any errors on 64-bit Linux, but the new changes speed up reading quite a bit.
