### ISSUE TITLE
Stale link in Unidentified Game Version error dialog

### ISSUE THREAD

**Issue by krenshala** [splintermind/Dwarf-Therapist#84]
Accidentally opened DT v23.3.0 even though I knew it didn't work with DF v0.40.06, and the error dialog reminded me I needed to post this.

The dialog has nothing wrong with it, except for the fact that the linked webpage is for the old version of DT, and points to http://code.google.com/p/dwarftherapist/wiki/SupportedGameVersions.  Definitely a low priority thing, but I wanted to get it on here.

**Comment by Hello71** [comment]
odd, the issue should close automatically. maybe it's because DF2014 isn't the HEAD ref.

splinterz, at this point with development effectively stopped on DF2013, maybe it would be a good idea to switch the default branch to DF2014. unlike renaming branches, this keeps all existing instructions correct (albeit possibly redundant) in that `git checkout DF2014` still checks out the correct code.

https://help.github.com/articles/closing-issues-via-commit-messages
https://help.github.com/articles/setting-the-default-branch

**Comment by splintermind** [comment]
What does that do to the current <code>master</code> branch? I was planning to branch the current master to DF2012 and then make the DF2014 the default branch. Maybe that's not the best solution?

**Comment by Hello71** [comment]
the default branch is the one that git checks out automatically on clone; github uses this for certain features like knowing when an issue has been "merged".

master is not special, it is just the default default branch. changing the default ref does not affect the branches at all.

**Comment by splintermind** [comment]
Alright I've changed the default branch, but that still doesn't answer my question about how I can change master to indicate that it's specifically for DF2012. I guess it just needs to be renamed now?

**Comment by Hello71** [comment]
I kinda lied; there's no real way to "rename" branches, but you can branch it to DF2012 and push without making any commits, then delete the master branch. `git checkout master; git checkout -b DF2012; git push DF2012; git branch -d master;  git push --delete origin master`

**Comment by splintermind** [comment]
this won't work?
<code>git branch -m master DF2012</code>
<code>git push origin DF2012</code>

**Comment by Hello71** [comment]
oh. huh. it seems that I lied again, but this time I wasn't aware of it. both need `git push --delete origin master` to delete the old branch though.

**Comment by splintermind** [comment]
Ok there we go, I think that should do it. Thanks for the help.
