### ISSUE TITLE
Crash when right clicking to add/edit a column in the gridview editor.

### ISSUE THREAD

**Issue by splintermind** [splintermind/Dwarf-Therapist#92]
[Crashlog](http://pastebin.com/Trb9TL1u)

[forum thread message](http://www.bay12forums.com/smf/index.php?topic=122968.msg5545019#msg5545019)

**Comment by Hello71** [comment]
groups is 0. probably deleted all the columns?

**Comment by fricy** [comment]
Narrowed down the problem, the first commit to crash this way is from july 3.

OK jun 26 - 7223b0f284523048df19e7c1296bcb6bb2c94ec8
CRASH july 3 - 7e8feb8cf50cb12cdf0b1c95ca35794ca2539baf

**Comment by splintermind** [comment]
Yeah I figured it was something to do with that re-ordering. Is it with any particular view, or after you copy a view? I'm still having a hard time getting it to crash on me.

**Comment by Hello71** [comment]
well, let's do some, uh... "static analysis", shall we.

the only division in that function is by groups, the second parameter, which means we need to go up the stack. there are a bunch of calls in `#1`, but unfortunately, we don't get line numbers, only instruction number (why would you ever want that).

```
m_cmh->add_sub_menus(m_custom_profs,2);
m_cmh->add_sub_menus(m_health,4);
m_cmh->add_sub_menus(m_labor,5);
m_cmh->add_sub_menus(m_roles,gdr->get_ordered_roles().count() / 20);
m_cmh->add_sub_menus(m_skill,gdr->get_ordered_skills().count() / 15);
m_cmh->add_sub_menus(m_super_labors,2);
m_cmh->add_sub_menus(m_trait,2);
//add_sub_menus(m_weapon,DT->get_DFInstance()->get_ordered_weapon_defs().count() / 15,true);
m_cmh->add_sub_menus(m_weapon,DT->get_DFInstance()->get_ordered_weapon_defs().count() / 15);
```

now, filtering out the ones that pass non-constant, possibly-zero values,

```
m_cmh->add_sub_menus(m_roles,gdr->get_ordered_roles().count() / 20);
m_cmh->add_sub_menus(m_skill,gdr->get_ordered_skills().count() / 15);
m_cmh->add_sub_menus(m_weapon,DT->get_DFInstance()->get_ordered_weapon_defs().count() / 15);
```

it would seem that, given this is integer division after all, the count of roles, skills, or weapon defs must be less than 20, 15, or 15 respectively.

**Comment by fricy** [comment]
To reproduce the crash: copy any grid, edit it, right click on anything in the right column.

**Comment by splintermind** [comment]
I must be going blind in my old age; I completely glossed over the division by zero on my first look at this. Great job with the crash report Fricy, just inattention on my part :P
