### ISSUE TITLE
Can't run precompiled DwarfTherapist on Linux

### ISSUE THREAD

**Issue by mushiden** [splintermind/Dwarf-Therapist#94]
When I run a precompiled version I get,

./DwarfTherapist: symbol lookup error: ./DwarfTherapist: undefined symbol: _ZN11QHeaderView10setVisibleEb

I assume I'm missing a package but I can't figure out which one. 
Running Mint 16 64bit.

**Comment by lethosor** [comment]
Do you have Qt installed? What version?

**Comment by vwood** [comment]
A lot of distros haven't got packages for libqt5, so you may well be screwed.

**Comment by mushiden** [comment]
Here is the results of  dpkg --get-selections | grep -i "qt" which should list any packages with qt in the name.

ipython-qtconsole               install
libaccounts-qt5-1               install
libdbusmenu-qt2:amd64               install
libntrack-qt4-1                 install
libpolkit-qt-1-1                install
libpoppler-qt4-4:amd64              install
libqt4-core                 install
libqt4-dbus:amd64               install
libqt4-dbus:i386                install
libqt4-declarative:amd64            install
libqt4-declarative:i386             install
libqt4-designer:amd64               install
libqt4-designer:i386                install
libqt4-dev                  install
libqt4-dev-bin                  install
libqt4-gui                  install
libqt4-help:amd64               install
libqt4-network:amd64                install
libqt4-network:i386             install
libqt4-opengl:amd64             install
libqt4-opengl:i386              install
libqt4-opengl-dev               install
libqt4-qt3support:amd64             install
libqt4-qt3support:i386              install
libqt4-script:amd64             install
libqt4-script:i386              install
libqt4-script-dbg               install
libqt4-scripttools:amd64            install
libqt4-scripttools:i386             install
libqt4-sql:amd64                install
libqt4-sql:i386                 install
libqt4-sql-sqlite:amd64             install
libqt4-svg:amd64                install
libqt4-svg:i386                 install
libqt4-test:amd64               install
libqt4-test:i386                install
libqt4-xml:amd64                install
libqt4-xml:i386                 install
libqt4-xmlpatterns:amd64            install
libqt4-xmlpatterns:i386             install
libqt53d5:amd64                 install
libqt5clucene5:amd64                install
libqt5concurrent5:amd64             install
libqt5core5:amd64               install
libqt5dbus5:amd64               install
libqt5declarative5:amd64            install
libqt5designer5:amd64               install
libqt5designercomponents5:amd64         install
libqt5gui5:amd64                install
libqt5help5:amd64               install
libqt5location5:amd64               install
libqt5network5:amd64                install
libqt5opengl5:amd64             install
libqt5printsupport5:amd64           install
libqt5qml5:amd64                install
libqt5quick5:amd64              install
libqt5script5:amd64             install
libqt5scripttools5:amd64            install
libqt5sensors5:amd64                install
libqt5sql5:amd64                install
libqt5sql5-sqlite:amd64             install
libqt5svg5:amd64                install
libqt5test5:amd64               install
libqt5v8-5:amd64                install
libqt5webkit5:amd64             install
libqt5widgets5:amd64                install
libqt5xml5:amd64                install
libqtassistantclient4:amd64         install
libqtcore4:amd64                install
libqtcore4:i386                 install
libqtgui4:amd64                 install
libqtgui4:i386                  install
libqtwebkit-dev                 install
libqtwebkit4:amd64              install
libqtwebkit4:i386               deinstall
libsignon-qt5-1                 install
python-qt4                  install
python-qt4-dbus                 install
qt-at-spi:amd64                 install
qt-sdk                      install
qt4-default                 install
qt4-designer                    install
qt4-dev-tools                   install
qt4-doc                     install
qt4-doc-html                    install
qt4-linguist-tools              install
qt4-qmake                   install
qt5-qmake                   install
qtbase5-dev:amd64               install
qtbase5-dev-tools               install
qtchooser                   install
qtcreator                   install
qtcreator-dbg                   install
qtcreator-dev                   install
qtcreator-doc                   install
qtscript-tools                  install
qtscript5-dev                   install
qttools5-dev                    install
qttools5-dev-tools              install
sni-qt:amd64                    install

**Comment by Hello71** [comment]
QHeaderView::setVisible(bool). you probably need to recompile.

**Comment by mushiden** [comment]
A fresh pull and compile works.
Any idea why the precompiled versions are failing in this manner?

**Comment by Hello71** [comment]
last I checked, splinterz doesn't distribute any compiled versions for linux; nor do I.
